import { describe, expect, it } from 'vitest';
import { assignResumeIds, collectIds, createIdFactory, slugify } from '../lib/ids';
import { createBlankResumeState, createDefaultResumeState, createResumeSection } from '../types/resume';

describe('slugify', () => {
  it('keeps CJK and lowercases ascii', () => {
    expect(slugify('XX科技有限公司')).toBe('xx科技有限公司');
    expect(slugify('Senior PM')).toBe('senior-pm');
  });

  it('collapses punctuation and trims the edges', () => {
    expect(slugify('Acme, Inc.')).toBe('acme-inc');
    expect(slugify('  -- 微信 / 抖音 -- ')).toBe('微信-抖音');
  });

  it('caps the length without leaving a dangling dash', () => {
    expect(slugify('abcdefghij', 4)).toBe('abcd');
    expect(slugify('ab cdefghij', 3)).toBe('ab');
  });
});

describe('createIdFactory', () => {
  it('keeps an id that is already set', () => {
    const next = createIdFactory();
    expect(next('work', 'Acme', 'work-acme-1')).toEqual({ id: 'work-acme-1', created: false });
  });

  it('suffixes collisions in encounter order', () => {
    const next = createIdFactory();
    expect(next('work', 'Acme').id).toBe('work-acme');
    expect(next('work', 'Acme').id).toBe('work-acme-2');
    expect(next('work', 'Acme').id).toBe('work-acme-3');
  });

  it('never hands out an id that a kept id already took', () => {
    const next = createIdFactory();
    next('work', 'Acme', 'work-acme');
    expect(next('work', 'Acme').id).toBe('work-acme-2');
  });

  it('falls back to the bare prefix when there is nothing to slug', () => {
    const next = createIdFactory();
    expect(next('item', '   ').id).toBe('item');
  });
});

describe('assignResumeIds', () => {
  it('never rewrites ids that are already set', () => {
    const resume = createDefaultResumeState();
    const first = assignResumeIds(resume).resume;
    const second = assignResumeIds(first).resume;

    expect(collectIds(second).map((entry) => entry.id)).toEqual(collectIds(first).map((entry) => entry.id));
  });

  it('is deterministic: the same content always produces the same ids', () => {
    const a = assignResumeIds(createBlankResumeState('张三')).resume;
    const b = assignResumeIds(createBlankResumeState('张三')).resume;
    const section = createResumeSection('work');
    const withSection = (base: typeof a) => ({ ...base, sections: [section] });

    expect(collectIds(assignResumeIds(withSection(a)).resume).map((entry) => entry.id)).toEqual(
      collectIds(assignResumeIds(withSection(b)).resume).map((entry) => entry.id),
    );
  });

  it('names ids from content when they are missing', () => {
    const resume = createBlankResumeState('张三');
    const section = createResumeSection('work');
    section.title = '工作经历';
    section.workEntries![0].organization = 'Acme';
    section.workEntries![0].positions[0].position = '产品经理';
    // A document written by hand (or by an agent) carries no ids at all. The
    // factory-generated uuids an editor would have left behind are preserved on
    // purpose, so blank them to exercise the naming path.
    section.id = '';
    section.workEntries![0].id = '';
    section.workEntries![0].positions[0].id = '';
    resume.sections = [section];

    const ids = collectIds(assignResumeIds(resume).resume).map((entry) => entry.id);
    expect(ids).toEqual(['sec-工作经历', 'work-acme', 'pos-产品经理']);
  });

  it('keeps ids generated by the editor, however unreadable', () => {
    const resume = createBlankResumeState('张三');
    const section = createResumeSection('work');
    section.workEntries![0].organization = 'Acme';
    resume.sections = [section];
    const original = section.workEntries![0].id;

    expect(assignResumeIds(resume).assigned).toEqual([]);
    expect(collectIds(assignResumeIds(resume).resume)[1].id).toBe(original);
  });

  it('replaces duplicate ids so patch addressing stays unambiguous', () => {
    const resume = createDefaultResumeState();
    resume.sections[0].workEntries![1].id = resume.sections[0].workEntries![0].id;

    const { resume: fixed, assigned } = assignResumeIds(resume);
    const ids = collectIds(fixed).map((entry) => entry.id);
    expect(new Set(ids).size).toBe(ids.length);
    expect(assigned.length).toBe(1);
  });

  it('regenerates everything with rewrite', () => {
    const resume = createDefaultResumeState();
    const { resume: rewrited, assigned } = assignResumeIds(resume, { rewrite: true });
    const randomIds = collectIds(resume).map((entry) => entry.id);

    expect(assigned.length).toBe(randomIds.length);
    for (const id of collectIds(rewrited).map((entry) => entry.id)) {
      expect(randomIds).not.toContain(id);
    }
  });

  it('does not mutate its input', () => {
    const resume = createDefaultResumeState();
    const before = JSON.stringify(resume);
    assignResumeIds(resume);
    expect(JSON.stringify(resume)).toBe(before);
  });

  it('leaves ids of nested positions unique across sections', () => {
    const resume = createDefaultResumeState();
    resume.sections = [createResumeSection('work'), createResumeSection('work')];
    const ids = collectIds(assignResumeIds(resume).resume).map((entry) => entry.id);
    expect(new Set(ids).size).toBe(ids.length);
  });
});

describe('collectIds', () => {
  it('walks sections, entries and nested positions with their paths', () => {
    const resume = createBlankResumeState('张三');
    const section = createResumeSection('work');
    section.workEntries![0].positions.push({ id: 'pos-2', position: '', startDate: '', endDate: '', highlights: [] });
    resume.sections = [section];

    const found = collectIds(assignResumeIds(resume).resume);
    expect(found.map((entry) => entry.path)).toEqual([
      '/sections/0',
      '/sections/0/workEntries/0',
      '/sections/0/workEntries/0/positions/0',
      '/sections/0/workEntries/0/positions/1',
    ]);
  });
});
